query MyQuery($entryId: Int!, $userId: Int) {
    getEntryById(id: $entryId, user_id: $userId) {
      data {
        actionStatus {
          clip
          follow
          reaction
          mute
        }
        caption
        comment
        createdTime
        curationSource
        description
        id
        view
        user {
          isAdmin
          id
          nickname
          profileImg
          title
        }
        tags
        thumbnail
        reactions {
          total
          items {
            caption
            count
            icon
            id
          }
        }
        spot {
          city
          country
          name
          region
          street
        }
        module {
          alias
          caption
          id
        }
        medias {
          type
          url
        }
      }
      result_code
    }
  }